<Project>
    <PropertyGroup>
        <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)yonder/obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
        <BaseOutputPath>$(MSBuildThisFileDirectory)yonder/bin/$(MSBuildProjectName)/</BaseOutputPath>
        <NuGetAudit>false</NuGetAudit>
    </PropertyGroup>
</Project>