<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <AssemblyName>Core.Imp</AssemblyName>
        <RootNamespace>Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Core\Core.csproj" />
      <ProjectReference Include="..\Util\Util.csproj" />
    </ItemGroup>

</Project>
