using System;
using System.Collections.Generic;
using Util.Collections;

namespace Model.Generation;

internal static class MetaConsts
{
    internal const string GeneratedFileHeader =
        """
        // <auto-generated/> \\ 
        #nullable enable
        
        /****************************************************************************\
         *                                                                          *
         *                   THIS FILE IS GENERATED AUTOMATICALLY                   *
         *                     DON'T MODIFY THIS FILE MANUALLY                      *
         *                                                                          *
        \****************************************************************************/
        """;


    internal const string ModuleDirPath        = "./Model_Imp";
    internal const string ImmDirPath           = ModuleDirPath + "/X-files";
    internal const string ImmAbstractsFilePath = ImmDirPath + "/ModelAbstractsImmImp.cs";
    internal const string ImmConceptFilePath   = ImmDirPath + "/ModelConceptImmImp.cs";
    internal const string ImmVisualityFilePath = ImmDirPath + "/ModelVisualityImmImp.cs";


    internal static readonly ImmDict<Type,string> SystemTypes =
        new Dictionary<Type,string>
        {
            { typeof(bool), "bool" },
            { typeof(byte), "byte" },
            { typeof(sbyte), "sbyte" },
            { typeof(ushort), "ushort" },
            { typeof(uint), "uint" },
            { typeof(int), "int" },
            { typeof(ulong), "ulong" },
            { typeof(long), "long" },
            { typeof(string), "string" },
        }.ToImmDict();

}
